### ISSUE TITLE
How to Run current script in node debug (Alt + D)?

### ISSUE THREAD

**Issue by ggslove** [tanepiper/SublimeText-Nodejs#45]
How to Run current script in node debug (Alt + D)?

**Comment by varp** [comment]
Yes @ggslove, you can hit (Alt+D) or (Ctrl+D), depending on your system, and you'll get desired :) But there are a more 3 serious problems: 
- you cannot communicate with an output of debugging session, for now
- hence the (Alt+D) is useless, for now
- node --debug deprecated since version 7.7.0
I'll need to do some observation for the first two problems.

**Comment by varp** [comment]
@ggslove the issue is fixed in new release 2.0.0
